### PR TITLE
Reordered clipboard commands so that pbcopy/pbpaste is tried first.

### PR DESCRIPTION
**Pull request by alexreg**

### CODE REVIEW

**Comment by akerl** [comment]
I'm not sure we really want to be relying on hash ordering being consistent, but also: can you clarify the goal in adjusting the ordering?

**Comment by alexreg** [comment]
So that the correct tool is used on OS X. It was recommended at https://github.com/defunkt/gist/issues/217.

**Comment by ConradIrwin** [comment]
This looks good to me, sorry for the delay.

@akerl most people are on modern-enough rubies that hash ordering can be relied upon nowadays.

**Comment by alexreg** [comment]
Thanks!

**Pull request merged**
