### PR TITLE
when gisting stdin default to filename 'a.rb' instead of '-'

### LINKED ISSUE #235: default to a.rb
When signed in and not using the `-a, --anonymous` flag: 
Untitled gists are automatically named `a.rb` instead of simply `-`.

### PR DESCRIPTION
**Pull request by phallstrom**
fixes #235

test plan:
  - ensure you're signed in (ie. have a token)

  % jot 5 | gist
  # check gist, filename should be 'a.rb'

  % gist Gemfile
  # check gist, filename should be 'Gemfile'

### CODE REVIEW

**Comment by ConradIrwin** [comment]
@phallstrom I think it should always default to `-` or if file extensions are important, then maybe`a.txt` (I don't want to assume everyone's using ruby just because the tool is written in ruby!).

This change breaks the ability to create a gist combining both an existing file and stdin:

```
gist header.txt -
```

**Comment by phallstrom** [comment]
@ConradIrwin Are you cool changing the previous default of `a.rb` to `-` as well? If you didn't want `-` looks like the website uses `gistfile.txt`.  Let me know...

**Comment by ConradIrwin** [comment]
Yup, I'm ok with `-`. `gistfile.txt` would be ok too. I'm not too fussed.

**Comment by phallstrom** [comment]
@ConradIrwin code modified to use `gistfile1.txt` and support both a file and stdin. Thanks!

**Comment by ConradIrwin** [comment]
Thanks again!

**Pull request merged**
