### PR TITLE
Load GitHub token from netrc if it's not in AuthTokenFile

### LINKED ISSUE #260: Add support for reading credentials from ~/.netrc
Various applications are able to read credentials from `~/.netrc` files, and there's a library offering support for reading and writing these files from ruby: https://github.com/heroku/netrc.

It would be good to consolidate credentials for the gist tool into that file and depend on a library built for managing credentials.

Thoughts?

### PR DESCRIPTION
**Pull request by biochimia**
Git, curl, and other tools already offer support for loading credentials
from ~/.netrc, namely when interacting with GitHub. This uses the netrc
gem to play along. This is implemented as a fallback, in case a token is
not found in the gist-specific file.

Fixes #260.

### CODE REVIEW

**Comment by ConradIrwin** [comment]
@biochimia we've historically avoided adding gem dependencies because it makes gist hard to use as a standalone app. That said, it may not matter anymore. Do you know if this will still work with `brew install gist`?

**Comment by biochimia** [comment]
I was just now looking how the json library is used from the vendor folder and exploring if something similar could be done for the netrc library.

I can also look at any issues that could come up with using homebrew. Do you have any pointers for how I would test that?

**Comment by biochimia** [comment]
Okay, I figured out how to update homebrew's HEAD branch for gist and can confirm that my branch breaks the homebrew installed gist.

On the other hand, netrc doesn't have additional external dependencies and is also licensed under the MIT license. Would it be okay to bring it under the vendor folder?

**Comment by biochimia** [comment]
I had another go at this, putting the `netrc.rb` library under `vendor/`, and skipping the gem dependency. I also updated the standalone script in `build/gist`, and tested installing from my branch with homebrew – I can confirm that that now works.

How do you feel about this approach?

**Comment by ConradIrwin** [comment]
Looks great, thank you! A few final things:

1. Could you please copy the license from the heroku project into netrc.rb (as required by the license)
2. Can you add some documentation to the README explaining how it works?

Happy to ship this, thanks for pushing it through :D

**Comment by biochimia** [comment]
Hi, thanks for merging this! I wanted to come back and finish the documentation, but let it drag for too long. Apologies for that!

I've now submitted #262 with the doc updates. Feel free to offer comments on that one to finish this off.

Cheers!

**Pull request merged**
