### PR TITLE
Add --delete option

### PR DESCRIPTION
**Pull request by rikas**
Simple feature requested in #211.

You can delete the gist with the ID or URL using `gist --delete [ ID | URL ]` and you must be logged in.

### CODE REVIEW

**Comment by rikas** [comment]
@ConradIrwin any comments? Is this good to go?

**Comment by vicqstream** [comment]
bump bump! @ConradIrwin

Nice one @rikas.

I've had to contact support to delete erroneously created anonymous gists twice now. it would be good to have a self service means to do this.

**Comment by rikas** [comment]
Thanks @vicqstream.

Seems like no one is merging this feature thou, since this pull request is from November 2015 :P

**Comment by budhrg** [comment]
Bump! @ConradIrwin .

Verified the PR. Works well as expected.
Command `gist --delete [ ID | URL ]` working fine.

:+1:

**Comment by originalsouth** [comment]
Any plans to ever merge this?

**Comment by ConradIrwin** [comment]
Done!

**Comment by originalsouth** [comment]
Awesome, thank you :)

**Pull request merged**
